version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/mime.types:/etc/nginx/mime.types
      - /opt/repos:/repo
    network_mode: host
    restart: always
  yumapi:
    image: finraos/yum-nginx-api:latest
    network_mode: bridge
    restart: always
    volumes:
      - /opt/repos:/repo
    ports:
      - "8080:8080"
    depends_on:
      - nginx
