[[constraint]]
  name = "github.com/go-ozzo/ozzo-routing"
  version = "2.1.4"

[[constraint]]
  name = "github.com/h2non/filetype"
  version = "1.0.5"

[[constraint]]
  branch = "master"
  name = "github.com/mutecomm/go-sqlcipher"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  name = "github.com/ulikunitz/xz"
  version = "0.5.5"

[prune]
  go-tests = true
  unused-packages = true
