version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.1
    working_directory: /go/src/github.com/FINRAOS/yum-nginx-api
    steps:
      - setup_remote_docker
      - run: git clone https://github.com/FINRAOS/yum-nginx-api.git -b go-rewrite .
      - run:
          shell: /bin/bash
          command: |
            cd yum-nginx-api
            make build
            make docker
      - run:
          shell: /bin/bash
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push finraos/yum-nginx-api:latest