version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.1
    working_directory: /go/src/github.com/FINRAOS/yum-nginx-api
    steps:
      - checkout
      - run: make docker
      - run:
          name: Docker push
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push finraos/yum-nginx-api:latest